# Automation ID: 1 - Automation to Develop

name: Automation to Develop

on:
  issues:
    types: [labeled]

jobs:
  check-and-deploy:
    if: github.event.label.name == 'done'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
      pull-requests: write
    steps:
      - name: Checkout develop
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0

      - name: Check if issue has deploy label
        id: check-label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          REPO=${{ github.repository }}
          
          # Get issue labels using GitHub API
          LABELS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER/labels" \
            | jq -r '.[].name')
          
          echo "Labels: $LABELS"
          
          if echo "$LABELS" | grep -q "a déployer sur main"; then
            echo "has_deploy_label=true" >> $GITHUB_OUTPUT
          else
            echo "has_deploy_label=false" >> $GITHUB_OUTPUT
          fi

      - name: Merge main into develop
        if: steps.check-label.outputs.has_deploy_label == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Pull latest develop
          git pull origin develop
          
          # Merge main
          if git ls-remote --heads origin main | grep -q 'refs/heads/main'; then
            git merge origin/main --no-ff -m "Auto-merge main into develop for issue #${{ github.event.issue.number }} (deploy label)"
            git push origin develop
            echo "Successfully merged main into develop and pushed."
          else
            echo "Main branch does not exist. Skipping merge."
            exit 1
          fi

      - name: Add comment to issue
        if: steps.check-label.outputs.has_deploy_label == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Deployment to develop completed via auto-merge from main branch.'
            })